export const commands = [
  { text: 'cat', link: '/commands/cat' },
  { text: 'cd', link: '/commands/cd' },
  { text: 'cowsay', link: '/commands/cowsay' },
  { text: 'cp', link: '/commands/cp' },
  { text: 'day', link: '/commands/day' },
  { text: 'exec', link: '/commands/exec' },
  { text: 'history', link: '/commands/history' },
  { text: 'kill', link: '/commands/kill' },
  { text: 'ls', link: '/commands/ls' },
  { text: 'mkdir', link: '/commands/mkdir' },
  { text: 'mv', link: '/commands/mv' },
  { text: 'neofetch', link: '/commands/neofetch' },
  { text: 'ping', link: '/commands/ping' },
  { text: 'ps', link: '/commands/ps' },
  { text: 'rm', link: '/commands/rm' },
  { text: 'top', link: '/commands/top' },
  { text: 'touch', link: '/commands/touch' },
  { text: 'unzip', link: '/commands/unzip' },
  { text: 'wget', link: '/commands/wget' },
  { text: 'which', link: '/commands/which' },
  { text: 'whoami', link: '/commands/whoami' },
  { text: 'qrcode', link: '/commands/qrcode' },
  { text: 'base64', link: '/commands/base64' },
]
